### ISSUE TITLE
use mupdf from a controller

### ISSUE THREAD

**Issue by phillamarmotte** [jogu/MuPDF-example#1]
Hi,
I've triyed to use mupdf like you did in your example and it works well.
But i can't make it works from a view controller instead of appdelegate. is it possible or do i need to do it from the app delegate.
thanks

**Comment by jogu** [comment]
Yes, it's possible. 

What happens when it doesn't work?

**Comment by phillamarmotte** [comment]
I copy paste your code in the ViewController and nothing happens, the MuDocumentController doesn't show anything only a blank page

**Comment by phillamarmotte** [comment]
- (void)viewDidLoad {
  [super viewDidLoad];
  
  NSLog(@"Controller");
  
  queue = dispatch_queue_create("com.artifex.mupdf.queue", NULL);
  
  screenScale = [[UIScreen mainScreen] scale];
  
  ctx = fz_new_context(NULL, NULL, ResourceCacheMaxSize);
  
  fz_register_document_handlers(ctx);
  
  NSString *file = [[NSBundle mainBundle] pathForResource:@"hello-world" ofType:@"pdf"];
  MuDocRef *doc;
  
  doc = [[MuDocRef alloc] initWithFilename:(char *)file.UTF8String];
  if (!doc) {
    NSLog(@"Cannot open document '%@'", file);
    return;
  }
  
  MuDocumentController *document = [[MuDocumentController alloc] initWithFilename:file path:(char *)file.UTF8String document: doc];
  
  [self.navigationController pushViewController:document animated:NO];

}

**Comment by jogu** [comment]
Pushing a UIViewController onto a navigation controller within viewDidLoad is not really a sane thing to do.

Why are you doing that? Just push the MuDocumentController onto the navigation controller instead of pushing whichever controller this code is in. Also make sure that self.navigationController and doc are non-nil.

**Comment by phillamarmotte** [comment]
i did that cause i tried : 
  UINavigationController *navigator = [[UINavigationController alloc] initWithRootViewController: document];
  [[navigator navigationBar] setTranslucent: YES];
  [[navigator toolbar] setTranslucent: YES];
  self.view.window.rootViewController = navigator;

and it didn't work

**Comment by jogu** [comment]
Yes, that is unlikely to work. I don't think you have understood what that code is doing and how it would fit into the rest of your app.

Can you post the full source code of your app into github as a repository? I can probably easily get it working if you do so. The way to integrate mupdf really depends how the rest of your app is built.

**Comment by phillamarmotte** [comment]
I did it.
I create a navigationController in the storyboard and everything is ok
Thanks for your time and your example

  queue = dispatch_queue_create("com.artifex.mupdf.queue", NULL);

  screenScale = [[UIScreen mainScreen] scale];

  ctx = fz_new_context(NULL, NULL, ResourceCacheMaxSize);

  fz_register_document_handlers(ctx);

  NSString *file = [[NSBundle mainBundle] pathForResource:@"hello-world" ofType:@"pdf"];
  MuDocRef *doc;

  doc = [[MuDocRef alloc] initWithFilename:(char *)file.UTF8String];
  if (!doc) {
    NSLog(@"Cannot open document '%@'", file);
    return;
  }

  MuDocumentController *document = [[MuDocumentController alloc] initWithFilename:file path:(char *)file.UTF8String document: doc];

  [self.navigationController pushViewController:document animated:false];

**Comment by jogu** [comment]
That all looks correct to me - nice one :) I'll close this then.
